version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: alukongo
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: piscineds
    ports:
      - "5433:5432"
